TRUTH = [
"Kebohongan apa yang terakhir kali kamu lakukan?",
"Apa hal paling memalukan yang pernah kamu lakukan saat kencan?",
"Pernahkah kamu secara tidak sengaja menabrak sesuatu (atau seseorang!) dengan mobil?",
"Sebutkan seseorang yang pura-pura kamu sukai tapi sebenarnya tidak kamu sukai.",
"Apa nama panggilanmu yang paling aneh?",
"Apa pengalaman paling menyakitkan yang pernah kamu alami?",
"Apa hal paling gila yang pernah kamu lakukan di transportasi umum?",
"Jika permintaanmu dapat terkabul, apa hal yang ingin kamu minta?",
"Jika kamu dapat memilih seseorang di dunia ini untuk menjadi Presiden Indonesia, siapakah orang tersebut dan apa alasannya?",
"Apa hal paling kejam yang pernah kamu katakan kepada orang lain?",
"Apa satu hal yang akan kamu lakukan jika kamu tahu tidak ada konsekuensinya?",
"Apa hal tergila yang pernah kamu lakukan di depan cermin?",
"Apa hal yang kamu suka lakukan dengan teman-temanmu yang tidak akan pernah kamu lakukan di depan pasangan?",
"Siapa yang paling membuatmu cemburu?",
"Pernahkah kamu berpura-pura sakit agar bisa keluar dari sebuah acara?",
"Siapa orang tertua yang pernah kamu kencani?",
"Berapa banyak foto selfie yang kamu ambil dalam sehari?",
"Berapa kali dalam seminggu kamu memakai celana yang sama?",
"Apakah Anda percaya pada takhayul?",
"Apa kebiasaanmu yang paling memalukan?",
"Kapan terakhir kali kamu meminta maaf? Dan untuk apa?",
"Pernahkah kamu pipis di kolam renang?",
"Apa hadiah termurah yang pernah kamu berikan kepada orang lain?",
"Apa hal paling aneh yang pernah kamu lakukan di tempat umum?",
"Pernahkah kamu berbohong mengenai usiamu?",
"Jika kamu harus menghapus satu aplikasi di ponsel,  manakah aplikasi yang akan kamu hapus?",
"Apa hal memalukan yang pernah menimpamu?",
"Berapa lama kamu pernah tidak mandi?",
"Siapa anggota keluarga yang paling menyebalkan dan tidak kamu sukai?",
"Pernahkah kamu berbohong kepada orang tua?",
"Berapa lama kamu pernah tidak menggosok gigi?",
"Pernahkah kamu memberikan hadiah kepada orang lain menggunakan hadiah yang pernah kamu terima?",
"Pernah kencan dengan teman satu kantor?",
"Apakah kamu masih memiliki rasa untuk mantan pacar?",
"Apa menu termurah yang pernah kamu beli di restoran?",
"Apa pekerjaan yang tidak pernah bisa kamu lakukan?",
"Jika kamu berganti gender selama sehari, apa yang akan kamu lakukan?",
"Berapa banyak aplikasi edit foto yang kamu miliki di ponsel?",
"Apa hal paling kekanak-kanakan yang masih kamu lakukan?",
"Kapan terakhir kali kamu mencampakkan seseorang?",
"Jika kamu harus memilih seseorang di ruangan ini untuk menjadi pasangan dalam sebuah game show, siapakah orangnya dan mengapa?",
"Apakah kamu akan berkencan dengan orang yang lebih pendek darimu?",
"Kapan terakhir kali kamu membuat orang lain menangis?",
"Jika kamu bisa menjadi tidak terlihat, apa hal terburuk yang akan kamu lakukan?",
"Apa hal dalam hidup yang kamu inginkan untuk diubah?",
"Jika kamu bisa berkencan dengan dua orang sekaligus dalam satu waktu, apakah kamu akan melakukannya? Dan mengapa?",
"Apa hari terbaik yang pernah kamu jalani?",
"Apa satu kemampuan yang ingin kamu miliki dalam hidup?",
"Siapa di ruangan ini yang kamu masukkan ke dalam kontak darurat?",
"Apa hal mengerikan yang pernah terjadi kepadamu?",
"Seberapa sering kamu mengganti sprei kasurmu?",
"Pernahkah kamu kentut di kolam renang?",
"Apa benda terakhir yang kamu sesali karena membelinya?",
"Apa mimpi teraneh yang pernah kamu alami?",
"Siapa yang akan kamu hubungi untuk membantu menguburkan tubuh seseorang?",
"Kapan terakhir kamu menangis dan kenapa?",
"Siapa orang yang ada di ruangan ini yang ingin kamu tukar kehidupannya dengan dirimu?",
"Apa ketakutan terbesarmu saat kecil?",
"Apa ketakutan terbesarmu saat ini?",
"Apa hal memalukan yang pernah ketahuan oleh orang tuamu?",
"Apa satu hal yang tidak akan pernah kamu lakukan walaupun akan diberi semua uang di dunia?",
"Jika kamu hanya bisa mendengarkan satu lagu sepanjang hidupmu, lagu apakah itu?",
"Apa video YouTube terakhir yang kamu tonton?",
"Kapan terakhir kali kamu pipis di celana?",
"Apa hal paling aneh yang pernah kamu lakukan di bioskop?",
"Apa kata yang paling kamu benci?",
"Siapa orang yang paling benci saat ini?",
"Pernahkah kamu mencuri?",
"Apa hal memalukan yang pernah kamu unggah di media sosial?",
"Apa hal paling aneh yang pernah kamu lakukan di kamar mandi?",
"Apa hal paling gila yang pernah kamu lakukan untuk menghindari tilang?",
"Kapan terakhir kali kamu ketahuan berbohong?",
"Pernahkah kamu bertengkar dengan seseorang?",
"Apakah kamu memiliki kemampuan tersembunyi? Apakah itu?",
"Apa saran terburuk yang pernah diberikan orang lain kepadamu?",
"Siapa orang terakhir yang menghubungimu?",
"Kapan terakhir kali rasanya kamu ingin memukul orang lain?",
"Apa bau yang paling buruk, namun kamu menyukainya?",
"Kapan terakhir kali kamu marah dan kenapa?",
"Apa hal paling tidak menyenangkan dari sekolah?",
"Apakah kamu tertarik melakukan operasi plastik?",
"Siapa orang terakhir yang kamu sampaikan ucapan “I love you”?",
"Pernahkah kamu membuat orang lain patah hati?",
"Apa gosip paling aneh mengenai dirimu yang pernah kamu dengar?",
"Pernahkah kamu muntah di tempat umum?",
"Kapan terakhir kali kamu ditolak?",
"Apa hal yang paling umum membuat orang lain salah paham terhadapmu?",
"Pernahkah kamu membuat orang lain mengalami cedera parah?",
"Apa tanggung jawab yang kamu harap tidak memilikinya?",
"Apa hal paling menakutkan yang pernah kamu lakukan?",
"Apa hal terindah yang pernah kamu lakukan?",
"Apa hal yang pernah kamu lakukan dan masih merasa bersalah sampai sekarang?",
"Pernahkah kamu diam-diam tidak menyukai temanmu?",
"Apa hal teraneh yang kamu koleksi?",
"Siapa orang di ruangan ini yang paling kamu tidak percayai?",
"Apa hal terbodoh yang pernah kamu lakukan untuk membohongi seseorang?",
"Apa hadiah terburuk yang pernah kamu terima dari orang lain?",
"Pernahkah kamu suka dengan bos atau guru?",
"Apa lagu yang paling sering kamu nyanyikan di kamar mandi?",
"Siapa yang akan kamu ajak untuk pergi ke pulau tidak berpenghuni dan kenapa?",
]


DARE = [
"Biarkan pemain lain memposting status di sosial milikmu?.",
"Lakukan rap gaya bebas selama 1 menit tentang peserta lain?.",
"Ciumlah ketiak setiap pemain lain?.",
"Ciumlah orang di sebelah kirimu?.",
"Peragakan tingkah laku pemain lain sampai seseorang dapat mengetahui siapa dia?.",
"Hubungi orang yang kamu sukai?.",
"Menari tanpa musik selama 1 menit?.",
"Lakukan jungkir balik?.",
"Biarkan orang di sebelah kananmu menggambar wajahmu?.",
"Berikan ponselmu kepada pemain lain untuk mengirimkan satu teks yang  mereka inginkan ke salah satu kontakmu?.",
"Minum jus lemon?.",
"Pecahkan sebutir telur di kepala?.",
"Bertukar pakaian dengan lawan jenis selama 2 ronde?.",
"Bertingkahlah seperti ayam sampai giliranmu berikutnya?.",
"Bicaralah dengan logat Batak sampai giliranmu berikutnya?.",
"Telepon seorang teman, berpura-puralah hari ini adalah hari ulang tahun mereka, dan nyanyikan lagu ”Selamat Ulang Tahun” untuknya?.",
"Lakukan tarian balet selama 1 menit?.",
"Mandi dengan tetap mengenakan pakaian?.",
"Ambil foto selfie di toilet dan unggah di media sosial?.",
"Akhiri setiap kalimat dengan kata ”tidak” hingga giliranmu berikutnya?.",
"Sebutkan nama orang terkenal yang mirip dengan setiap pemain?.",
"Menarilah seolah-olah hidupmu bergantung padanya?.",
"Makanlah sebungkus saus pedas secara langsung?.",
"Tuangkan es ke dalam celana?.",
"Berputarlah 12 kali dan cobalah berjalan lurus?.",
"Kenakan penutup mata dan sentuh wajah pemain lain hingga kamu dapat mengetahui siapa dia?.",
"Makanlah telur mentah?.",
"Biarkan pemain di sebelah kananmu mengulang riasan wajahmu?.",
"Berpura-puralah menjadi tupai sampai giliranmu berikutnya?.",
"Siramkan seember air dingin ke kepalamu?.",
"Jilat sebatang sabun?.",
"Makan satu sendok makan sambal?.",
"Coba berbicara tanpa menutup mulut?.",
"Biarkan seseorang mengecat kukumu sesuka hati?.",
"Lakukan stand up comedy selama 5 menit?.",
"Bergoyang seperti bebek sampai giliranmu berikutnya?.",
"Menyanyikan lagu kesukaan sambil menari?.",
"Tunjukkan foto paling memalukan yang ada di galeri ponsel?.",
"Tunjukkan lima orang terakhir yang kamu kirimkan pesan dan apa isinya?.",
"Kirimkan pesan berisi “ Aku rindu” kepada mantan pacar?.",
"Lakukan push up 100 kali?.",
"Masukkan tiga es batu ke dalam mulut hingga mencair?.",
"Tunjukkan pesan yang ada di DM Instagram?.",
"Tutup mata hingga giliranmu berikutnya?.",
"Coba tunjukkan dompetmu dan keluarkan semua isinya?.",
"Berpura-pura menjadi orang di sebelah kananmu selama 10 menit?.",
"Makan camilan tanpa menggunakan tangan?.",
"Bisikkan sebuah rahasia kepada orang di sebelah kirimu?.",
"Katakan dua hal paling jujur tentang semua orang yang ada di dalam ruangan?.",
"Ceritakan kisah paling menyedihkan yang kamu ketahui?.",
"Tunjukkan foto favorit dirimu sendiri yang ada di ponsel?.",
"Posting draft video yang ada di aplikasi TikTok?.",
"Buat rap tentang buku favoritmu?.",
"Lakukan 50 kali push up?.",
"Ungkapkan apa yang kamu pikirkan tentang apa yang akan dilakukan semua orang di ruangan ini dalam waktu lima tahun ke depan"
"Berikan pujian secara langsung kepada semua orang yang ada di ruangan ini?.",
"Biarkan orang-orang yang ada di ruangan menata rambutmu dan biarkan seperti itu selama permainan berlangsung?.",
"Hanya berbicara dengan berbisik selama 10 menit ke depan?.",
"Katakan sebuah rahasia tentang seseorang di dalam ruangan tapi jangan ungkapkan namanya?.",
"Makan satu buah bawang putih?.",
"Ulangi semua perkataan orang di sebelah kirimu hingga giliranmu berikutnya?.",
"Berikan ‘like’ pada 15 postingan pertama yang muncul di halaman beranda Instagram?.",
"Makan satu sendok penuh garam?.",
"Menyanyikan dua lagu tanpa ekspresi?.",
"Biarkan orang lain menggelitikimu dan tahan untuk tidak tertawa?.",
"Coba membuat dirimu sendiri menangis sekarang?.",
"Mencoba tarian TikTok yang muncul di halaman TikTok?.",
"Tahan untuk tidak tertawa selama 10 menit ke depan?.",
"Untuk 10 menit ke depan, setiap orang yang bertanya kepadamu, kamu jawab dengan gonggongan?.",
"Tutup mata dan biarkan seseorang di ruangan ini menyuapkan sesuatu yang berasal dari kulkas?.",
"Baca dengan keras lima hal yang kamu cari dari riwayat pencarian?.",
"Pijat kaki orang yang ada di kananmu?.",
"Ceritakan hal memalukan yang pernah kamu lakukan?.",
"Kupas pisang menggunakan kaki?.",
"Masukkan camilan ke dalam mulut sebanyak yang kamu bisa?.",
"Kenakan pakaian secara terbalik sepanjang sisa permainan?.",
"Senyum selebar-lebarnya dan tahan selama dua menit?.",
"Duduk di pojok ruangan tanpa berkata sepatah kata pun selama 10 menit?.",
"Makan satu sendok penuh lada?.",
"Makan bawang mentah seperti makan apel?.",
"Bertukar sepatu dengan orang yang duduk di sebelah kanan?.",
"Telpon orang yang terakhir kamu kirimkan pesan?.",
"Berikan komentar pada lima Instagram story yang muncul di beranda?.",
"Lakukan live di Instagram?.",
"Unggah foto random di Instagram?.",
"Berikan komentar berupa emoticon api pada lima unggahan teratas di beranda Instagram?.",
"Cium kaki pemain lain?.",
"Biarkan pemain lain melihat ponselmu selama satu menit?.",
"Tunjukkan tarian terbaik yang bisa kamu lakukan?.",
"Biarkan orang lain menggambar tato menggunakan spidol permanen di tanganmu?.",
"Lakukan prank telepon kepada salah satu anggota keluarga?.",
"Makan tiga buah es batu sekaligus?.",
"Makan pisang yang dicampur dengan saus sambal?.",
"Minum satu gelas air selama 5 detik?.",
"Berbicara di depan bantal layaknya berbicara dengan orang yang kamu sukai?.",
"Temukan cinta pertamamu lewat Instagram dan kirim pesan kepadanya?.",
"Bernyanyi seperti pemain opera selama lima menit?.",
"Pura-pura sedang berada di dalam air selama 10 menit?.",
"Tunjukkan riwayat video yang telah ditonton di YouTube?.",
"Tunjukkan pesan favorit dari orang yang disukai?.",
]
